### ISSUE TITLE
App with high CPU usage/mem/hangs possibly after wake

### ISSUE THREAD

**Issue by dieb** [orchetect/MenuBarExtraAccess#11]
### Bug Description, Steps to Reproduce, Crash Logs, Screenshots, etc.

Hi there, first of all thank you for MenuBarExtraAccess!

Problem: my macOS app starts showing high CPU/mem usage possibly after computer is awaken from sleep. Profiling indicates some good amount of time spent on NSStatusItem.

I think it might be the way I'm using MenuBarExtraAccess. I'm reproducing it consistently putting the computer to sleep and then clicking on the app in the menu bar. Edit: now I'm able to consistently trigger it by simply clicking on the app in the menu bar, don't even need to put it to sleep.

Would appreciate any help or pointers you may have.  Code and profiling screenshots can be found below.

![Screenshot 2024-02-08 at 3 18 09 PM](https://github.com/orchetect/MenuBarExtraAccess/assets/75843/ef13f973-25b6-43f6-8a1d-a6831fa28c3c)

## Environment

Environment: macOS Sonoma 14.2.1, MBP M1 2020, one external monitor
System settings: menu bar auto-hide enabled

## Code

This is sample code that very closely resembles how my app uses MenuBarExtraAccess and MacControlCenterUI:

```swift
import SwiftUI
import MacControlCenterUI
import SettingsAccess

@main
struct MyAppApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate: AppDelegate
    @State var isMenuPresented: Bool = false

    var body: some Scene {
        Settings {
            SettingsView().environmentObject(appState)
        }

        MenuBarExtra() {
            MenuBarView(isMenuPresented: $isMenuPresented)
                .openSettingsAccess()
                .environmentObject(appState)
        } label: {
            Label(Constants.appName, image: "MenuBarIcon")
        }
        .menuBarExtraStyle(.window)
        .menuBarExtraAccess(isPresented: $isMenuPresented)
    }
}
```

```swift
import SwiftUI
import MacControlCenterUI
import Combine
import OSLog

struct MenuBarView: View {
    @Environment(\.openSettings) private var openSettings
    @Binding var isMenuPresented: Bool

    @State private var counter: Int = 0
    @State private var isCounterEnabled: Bool = false
    @State private var timer: AnyCancellable?

    func update() {
        // Update counter every second only when the UI is being presented
        counter += 1
    }

    func startTimer() {
        timer = Timer.publish(every: 1, on: .main, in: .common)
            .autoconnect()
            .sink { _ in update() }
    }

    func stopTimer() {
        timer?.cancel()
        timer = nil
    }

    var body: some View {
        MacControlCenterMenu(isPresented: $isMenuPresented) {
             VStack {
                 Toggle("Enable", isOn: $isCounterEnabled)
                 Text("\(counter)")
             }
        }
        .onChange(of: isMenuPresented) { _ in
            if isMenuPresented {
                if isCounterEnabled: {
                    startTimer()
                }
            } else {
                stopTimer()
            }
        }
    }
}
```

## Screenshots

52.28 s   36.8%	1.00 ms	 	                     -[NSStatusItem _updateReplicantsUnlessMenuIsTracking:]

![Screenshot 2024-02-08 at 4 09 30 PM](https://github.com/orchetect/MenuBarExtraAccess/assets/75843/25b2b837-d30f-401d-82b5-eeb349ba3ba1)

MenuBarExtras.setupEventsMonitor

![Screenshot 2024-02-08 at 4 08 18 PM](https://github.com/orchetect/MenuBarExtraAccess/assets/75843/51c749a1-0800-4176-8b7e-ed5ac6fbdf39)

`statusItem.for(:)`

![Screenshot 2024-02-08 at 4 07 20 PM](https://github.com/orchetect/MenuBarExtraAccess/assets/75843/a9566c0e-8f32-4b1c-bc68-4a507acba0b6)

![Screenshot 2024-02-08 at 3 51 57 PM](https://github.com/orchetect/MenuBarExtraAccess/assets/75843/db12c976-168f-48e9-adf9-cf5090836639)

**Comment by orchetect** [comment]
Thanks for the detailed reporting. I may not have time to delve into this right away but there may be some ways to mitigate what's happening.

There are less than ideal inefficiencies necessary (mirror introspection and dynamic lookups) to even get MenuBarExtraAccess to provide its essential functionality in the first place, because of how handcuffed Apple makes their API. So it may be possible to improve but not clear if it can be totally resolved.

**Comment by dieb** [comment]
Hey there, thanks for the quick reply. I tracked down the issue in my app and it wasn't related to the timer nor MenuBarExtraAccess. 

It was caused by a using public computed property from another object. It perpetually triggered new renders of the view. Please don't ask me why, I was probably tired 😂 

```swift
class AppState: ObservableObject {
    @AppStorage("something") var something = 0

    var somethingDynamic: Int {
       something + 1
    }
}
```


```swift
struct SomeView: View {
    @EnvironmentObject private var appState: AppState

    var body: some View {
        Text("\(appState.somethingDynamic)")
    }
}
```

**Comment by orchetect** [comment]
Hey no sweat, glad you found it.
