### ISSUE TITLE
Compilation errors in a totally fresh app

### ISSUE THREAD

**Issue by pooriajr** [orchetect/MenuBarExtraAccess#15]
### Bug Description, Steps to Reproduce, Crash Logs, Screenshots, etc.

![CleanShot 2024-10-13 at 18 24 30@2x](https://github.com/user-attachments/assets/87488eef-ae69-47c4-a78b-cc3a0ecf7c7f)

Description: 
I get compilation errors just importing the package into a fresh app

Steps to reproduce:
Create a brand new test SwiftUI app in XCode (v 15.4)
File > Add package dependencies
Find and add this package via the url from readme
Try to build the app

At that point I get the errors. I have tried restarting the computer, clearing the build with command shift K, downloaded the latest xcode command line tools.

I'm still on Sonoma 14.0, not on Sequoia, not sure if that matters? 

Thank you so much for any help, this package will be a lifesaver if I can get it to work! 🙏

**Comment by orchetect** [comment]
Fixed in release 1.1.3.

**Comment by pooriajr** [comment]
Wow awesome, thank you!
