### ISSUE TITLE
Command SwiftCompile Failed - Main Actor-Isolated Context Issues in Xcode 15

### ISSUE THREAD

**Issue by umarbuild** [orchetect/MenuBarExtraAccess#17]
### Bug Description, Steps to Reproduce, Crash Logs, Screenshots, etc.

![image](https://github.com/user-attachments/assets/9d3697e0-393f-4089-b1b8-21829f99cb56)

#### **Description:**

After installing the app dependencies, I am unable to build the project in Xcode 15. The build process fails with the following errors:

1. **Command SwiftCompile failed with a nonzero exit code.**
2. Multiple errors related to main actor-isolated calls in a synchronous nonisolated context, specifically:
   
   - `Call to main actor-isolated static method 'window(for:)' in a synchronous nonisolated context.`
   - `Call to main actor-isolated static method 'togglePresented(for:)' in a synchronous nonisolated context.`
   - `Call to main actor-isolated static method 'setPresented(for:state:)' in a synchronous nonisolated context.`

#### **Steps to Reproduce:**

1. Open the project in Xcode 15.
2. Attempt to build the project (`Cmd + B`).
3. The build fails with the errors listed above.

#### **Expected Behavior:**

The app should build successfully in Xcode 15.

#### **Actual Behavior:**

The build fails due to multiple errors involving calls to main actor-isolated methods from a synchronous nonisolated context.

#### **Environment:**

- **Xcode Version:** 15
- **Swift Version:** 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
- **macOS Version:** 14.2.1

**Comment by orchetect** [comment]
The compatibility updates for Swift 6 in release 1.2.0 may have bumped the Xcode version requirement as well. Let me check and see what needs adjusting.

**Comment by orchetect** [comment]
I can see what's going on. In Xcode 15, SwiftUI's `View` and `Scene` are not implicitly `@MainActor` but in Xcode 16 they are.

I can push an update that resolves Xcode 15 builds soon.

**Comment by orchetect** [comment]
Fixed in release 1.2.1.
