### ISSUE TITLE
doesn't work with `@main final class MyApp: App`

### ISSUE THREAD

**Issue by damnever** [orchetect/MenuBarExtraAccess#9]
Thank you for creating this library, it is incredibly useful. 

I am new to SwiftUI and have been conducting some experiments, I encountered an issue when I changed the default `@main struct MyApp: App` to `@main final class MyApp: App`. The MenuBarExtraAccess ceased functioning. When I reverted back to the original code, it started working again.

**Comment by damnever** [comment]
I will close this for the moment to further acquaint myself with Swift and SwiftUI.


The reason:
Accessing State's value outside of being installed on a View. This will result in a constant Binding of the initial value and will not update.

**Comment by orchetect** [comment]
`MyApp` has to be a struct, not a class. And there's no reason to mark it `final`.
